### ISSUE TITLE
Layout problem with long text

### ISSUE THREAD

**Issue by Jisagi** [smallwat3r/shhh#175]
Hi, after the new 150 character limit is now changeable, I did find a slightly problematic behaviour for text which does have any newlines. Here are two exmaples with lorem ipsum 50 words and 100 words <https://imgur.com/a/5JJT6BW>. As long as the text isn't too long before the next newline character, its fine, but otherwise the shown behaviour happens. You can also not scroll the the right, so its a breaking problem if the text gets any longer than the examples. Maybe something like a forced wrap would be a possible solution.

**Comment by smallwat3r** [comment]
Hi @Jisagi, can you try with pulling the latest master branch? I've seen this issue yesterday and it "should" now be fixed!

**Comment by Jisagi** [comment]
Thanks for the very fast response. It does indeed work now, awesome work man!
I'm not sure if I like the new font, but that part is debateable ;D

**Comment by smallwat3r** [comment]
Yeah I'm not sure about the font either to be honest... 😄

I though because Shhh is mostly used to share passphrases, snippets and/or certs it would be more appropriate to use a monospace font to write and display them (so users can easily distinguish characters like 0 and O etc). I used Hack as this is a widely used font in programming and it had an OFL license. I might experiment with other monospace fonts that would better. Feel free to share any that you think would look great :)

**Comment by Jisagi** [comment]
Haha, yeah I get what the idea was and I can agree on that part. The readability def increases for many coding things. The only location I was confused about it (at first), was the two dropdown boxes where it looked like the font didn't load. I wasn't sure if it was me, because I was fiddling with basic auth in apache and forgot allow /static/ for the fonts and such so I first thought it was me breaking it.
Maybe both the text input (not the password input) as well as the displayed secret message on the $HOST/r/... page could use the hack font and the rest the old one for better readabe "normal" text/numbers. That is just an diea though, I personally don't really care as mucha bout a font, as long as its not wingdings ;D
