### ISSUE TITLE
How to deploy?

### ISSUE THREAD

**Issue by Coderdude112** [smallwat3r/shhh#234]
In the README for this project it states the following:

> These instructions are for development purpose only. For production use you might want to use a more secure configuration.

I don't see any other instructions on how to deploy shhh. Is it a problem if I use the instructions given in the README for a production server? If not why?

**Comment by smallwat3r** [comment]
Hi @Coderdude112 and sorry for the late reply

Indeed, the README instructions to launch Shhh locally are mostly for development purposes. But you can still use the provided Dockerfile to build and host a container ready for production use.

It will also depend on the use you will make of Shhh (personal, enterprise etc) and where you want to deploy it.

For example, for a production-ready deployment in a Cloud Provider like AWS, I would:
- Host an Shhh container in something like `ECR` (Amazon Elastic Container Registry)
- Deploy it on an `ECS` (Amazon Elastic Container Service) instance
- Use `RDS` (Amazon Relational Database Service) for the DB service

But if it's for your personal use only, you could also just host the application on your own device, such as a Raspberry Pi, using the README instructions, and making sure to follow best practices in terms of security when setting up your web server. I would recommend also setting up Nginx.

Or ultimately and probably the simplest solution, you can use the "Deploy to Heroku" button in the README. That will build your own instance of Shhh in a production-ready environment for free (but bear in mind because it's free, it can come with poor performance from both the web server and the database). But you can then tweak and upgrade the services in Heroku if you need/want to.

Hope this answers your questions? 

Please feel free to close this ticket, and let me know if you would like more information.

**Comment by Coderdude112** [comment]
Thanks @smallwat3r! This clears up all of my questions!!
