### ISSUE TITLE
Dockerfile is broken

### ISSUE THREAD

**Issue by Coderdude112** [smallwat3r/shhh#238]
Hi, the dockerfile is currently broken.

It seems to be an issue that alpine Linux is experiencing as noted by [this](https://github.com/alpinelinux/docker-alpine/issues/98) issue.

Not sure if there is anything @smallwat3r can do, but thought to post here in case anyone else if having problems

**Comment by smallwat3r** [comment]
@Coderdude112 while trying to replicate this issue, I noticed another bug which I fixed in #241.

I was then able to successfully build the Shhh image. Please can you retry from the latest master branch? 

If it still doesn't work, can you share the error logs you get while building the Shhh container?

**Comment by Coderdude112** [comment]
Sorry for the late reply, I was able to build shhh without a problem on my main server but am still having problems on my raspberry pi. Not sure if this is an issue with the dockerfile though, it could be something else.

**Comment by smallwat3r** [comment]
@Coderdude112 I will close this issue for now. But please feel free to reopen it if needed!
