### ISSUE TITLE
Containerization

### ISSUE THREAD

**Issue by AustinTSchaffer** [smallwat3r/shhh#3]
Would you be interested in a `Dockerfile` and a `docker-compose.yml`?

Since the app already gets its configurations from environment variables, getting the app working in a container environment would be a natural fit. Just wondering if you're interested in that kind of thing.

Also, with adding a `docker-compose.yml`, I'd be interested in adding some MySQL migrate scripts, so that it's easier to get a database set up from source.

Cheers,
Austin

**Comment by smallwat3r** [comment]
@AustinTSchaffer these are really great ideas 
Getting the app to run in a container would be amazing, actually I was thinking about doing it
Please feel free to contribute to the project!

Matthieu

**Comment by AustinTSchaffer** [comment]
On it boss.

**Comment by AustinTSchaffer** [comment]
@smallwat3r, I'm having issues with getting the project to run, on both my bare laptop and within a container, while following your README instructions. I'm seeing a jinja2 error, indicating that it's having trouble finding the templates folder.

https://github.com/AustinTSchaffer/shhh/tree/user/ats/dockerandmysql

I've pushed up a branch that contains a Dockerfile and a docker-compose.yml along with a few other incidental changes, in case you'd like to debug the container configuration. The changes are not quite ready for a PR, but figured I'd share the intermediate commits. I'm at work right now so I can't take the time to debug the import and path structure at the moment, but I can when I get home if you need me to. My editor is giving me complaints on all of the `from ... import` lines, which might be a clue. I've attached the logs from the container and the saved HTML that is generated when you go to `http://localhost/create`. You can view it in a browser if you rename the extension to `.html`.

Best,
Austin

[applogs.txt](https://github.com/smallwat3r/shhh/files/3626973/applogs.txt)

[jinja2.exceptions.TemplateNotFound.txt](https://github.com/smallwat3r/shhh/files/3627013/jinja2.exceptions.TemplateNotFound.txt)

**Comment by smallwat3r** [comment]
Thanks @AustinTSchaffer - I just realized that there is a typo in the filename [_under_block_ui.html](https://github.com/smallwat3r/shhh/blob/master/shhh/front/shared_templates/_dom_block_ui.html), indeed `_under_block_ui.html` should be remaned `_under_block_UI.html` (with UI in uppercase).

I can't test right now but this should fix the issue. I will try later on tonight. Weird thing is that it was still working in my local - even with the typo.

Regarding the imports, this shouldn't cause any issues as the app is run as a module. That's why all the app configuration (blueprints etc.) are located under `__init__.py` and we need to launch it from the previous directory. When I was using VsCode the editor didn't like it as well and imports were flag as error - don't really know why as this works well.

By the way your branch looks good! Thanks for doing this!

Matthieu

**Comment by smallwat3r** [comment]
@AustinTSchaffer found a bit of time and tested running it from your branch using `docker-compose` after fixing the typo and everything work's fine!

**Comment by AustinTSchaffer** [comment]
🎉

You're using Mac right? I only guessed based on the DS_Store in the gitignore. I'm using Ubuntu, so differences in case sensitive file names, I guess. I'll rebase and check it out and see if it's all working on my end

**Comment by smallwat3r** [comment]
Well guessed - you're right that's probably why. Perfect - let me know if all good
